# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_geo_to_h3 <- function(latlng, res) {
    .Call(`_h3_rcpp_geo_to_h3`, latlng, res)
}

rcpp_h3_to_geo <- function(h3s) {
    .Call(`_h3_rcpp_h3_to_geo`, h3s)
}

rcpp_h3_to_geo_boundary <- function(h3s) {
    .Call(`_h3_rcpp_h3_to_geo_boundary`, h3s)
}

#' Number of unique H3 indexes at the given resolution.
#' @param res numeric vector; resolution between 0 and 15
#' @return numeric vector
#' @export
num_hexagons <- function(res) {
    .Call(`_h3_num_hexagons`, res)
}

rcpp_k_ring <- function(h3s, radius) {
    .Call(`_h3_rcpp_k_ring`, h3s, radius)
}

#' Get the grid distance between H3 addresses.
#' @param origin character; origin H3 index
#' @param destinations character vector of H3 destination indexes
#' @return numeric vector
#' @export
h3_distance <- function(origin, destinations) {
    .Call(`_h3_h3_distance`, origin, destinations)
}

rcpp_k_ring_distances <- function(h3s, radius) {
    .Call(`_h3_rcpp_k_ring_distances`, h3s, radius)
}

